### ISSUE TITLE
Lenovo Legion 7 methods not working

### ISSUE THREAD

**Issue by gavsiu** [thiagotei/linux-realtek-alc287#1]
Are there other requirements? Does this work with Pulse Audio? I'm using Pulse Audio for bluetooth headset compatibility.

Method 1 does nothing.

Method 2 returns an error:
```
sudo python3 realtek-verb-tools/applyverbs.py verbs-working.txt
Applying verbs...
Traceback (most recent call last):
  File "/home/gavsiu/Downloads/realtek-verb-tools/applyverbs.py", line 39, in <module>
    result = subprocess.run(args, stderr=subprocess.DEVNULL, stdout=subprocess.PIPE).stdout.decode('utf-8')
  File "/usr/lib/python3.9/subprocess.py", line 505, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'hda-verb'
```

Legion 7i 15" 81YT0039US
Host: 81YT Lenovo Legion 7 15IMH05

**Comment by thiagotei** [comment]
Yes, there is!  You have to install the `alsa-tools` to have the `hda-verb`. Let me update the text. Thanks for the heads-up!

**Comment by thiagotei** [comment]
@gavsiu, please let us know if that worked out for you! Which Linux and kernel are you using?

**Comment by thiagotei** [comment]
The link for the patch was downloading some html and not the patch content. It is fixed. I've tested in ubuntu 20.04 kernel 5.8.0-55 and worked.
